services:
  - type: web
    name: tikflow-commerce
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WILLOW_REQUIRE_HEIF
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: tikflow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CELERY_BROKER_URL
        value: "memory://"
      - key: CELERY_RESULT_BACKEND
        value: "cache"

databases:
  - name: tikflow-db
    databaseName: tikflow
    plan: free
