# Generated by Django 4.2.7 on 2025-11-04 17:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop', '0003_alter_customer_phone_alter_orderitem_price'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('featured', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('max_items', wagtail.blocks.IntegerBlock(default=8, max_value=24, min_value=1, required=False))])), ('grid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('category_slug', wagtail.blocks.CharBlock(help_text='Slug категории для фильтрации (опционально)', required=False)), ('show_prices', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('testimonials', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('author', wagtail.blocks.CharBlock(required=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(default='Заказать'))]))], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_pages', to='eshop.product')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
