# Generated by Django 4.2.7 on 2025-11-05 10:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('old_price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cta_text', wagtail.blocks.CharBlock(default='Замовити зараз', required=False)), ('cta_anchor', wagtail.blocks.CharBlock(help_text='Якорь ссылки, например #form', required=False))])), ('gallery', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])), ('video', wagtail.blocks.StructBlock([('youtube_id', wagtail.blocks.CharBlock(help_text='YouTube ID, например wKj3LlQ89IA', required=True)), ('height', wagtail.blocks.IntegerBlock(default=540, required=False))])), ('text', wagtail.blocks.StructBlock([('html', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr']))])), ('benefits', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Головні переваги', required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('steps', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Як замовити?', required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock())])))])), ('form', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='ЗАЛИШИТИ ЗАЯВКУ', required=False)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('submit_text', wagtail.blocks.CharBlock(default='Залишити заявку', required=False))]))], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
