# Generated by Django 4.2.7 on 2025-11-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_historicalorder_conversion_value_and_more'),
        ('landing', '0002_productlandingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlandingpage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landing_pages', to='eshop.product'),
        ),
    ]
