# Generated by Django 4.2.7 on 2025-11-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_ordersuccesspage_alter_productlandingpage_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersuccesspage',
            options={'verbose_name': 'Order Success Page', 'verbose_name_plural': 'Order Success Pages'},
        ),
        migrations.AlterModelOptions(
            name='productlandingpage',
            options={'verbose_name': 'Product Landing Page', 'verbose_name_plural': 'Product Landing Pages'},
        ),
    ]
