# Generated by Django 4.2.7 on 2025-11-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_ordersuccesspage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlandingpage',
            name='success_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.ordersuccesspage'),
        ),
    ]
