# Generated by Django 4.2.7 on 2025-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_productlandingpage_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlandingpage',
            name='font_family',
            field=models.CharField(choices=[('system', 'System Default'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('montserrat', 'Montserrat')], default='system', max_length=20),
        ),
    ]
