# Generated by Django 4.2.7 on 2025-11-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_productlandingpage_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlandingpage',
            name='body_line_height',
            field=models.DecimalField(decimal_places=2, default=1.3, max_digits=3),
        ),
        migrations.AddField(
            model_name='productlandingpage',
            name='body_weight',
            field=models.CharField(choices=[('300', '300'), ('400', '400'), ('500', '500')], default='300', max_length=3),
        ),
        migrations.AddField(
            model_name='productlandingpage',
            name='heading_line_height',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=3),
        ),
        migrations.AddField(
            model_name='productlandingpage',
            name='heading_weight',
            field=models.CharField(choices=[('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800')], default='600', max_length=3),
        ),
        migrations.AddField(
            model_name='productlandingpage',
            name='title_line_height',
            field=models.DecimalField(decimal_places=2, default=1.3, max_digits=3),
        ),
        migrations.AddField(
            model_name='productlandingpage',
            name='title_weight',
            field=models.CharField(choices=[('300', '300'), ('400', '400'), ('500', '500'), ('600', '600')], default='400', max_length=3),
        ),
    ]
