# Generated by Django 4.2.7 on 2025-11-06 11:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alter_productlandingpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlandingpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('old_price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cta_text', wagtail.blocks.CharBlock(default='Замовити зараз', required=False)), ('cta_anchor', wagtail.blocks.CharBlock(default='#form', help_text='Якорь ссылки, например #form', required=False)), ('use_product_image', wagtail.blocks.BooleanBlock(default=True, help_text='Если задан product у страницы — использовать его изображение', required=False)), ('use_product_price', wagtail.blocks.BooleanBlock(default=True, help_text='Если задан product у страницы — использовать его цену', required=False))])), ('gallery', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])), ('video', wagtail.blocks.StructBlock([('youtube_id', wagtail.blocks.CharBlock(help_text='YouTube ID, например wKj3LlQ89IA', required=True)), ('height', wagtail.blocks.IntegerBlock(default=540, required=False))])), ('animated', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Загрузите GIF для анимации', required=True)), ('alt', wagtail.blocks.CharBlock(help_text='Alt-текст (опционально)', required=False)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], help_text='Выравнивание блока на странице', required=False))])), ('text', wagtail.blocks.StructBlock([('html', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr']))])), ('promo', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.TextBlock(required=True)), ('price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('old_price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('cta_text', wagtail.blocks.CharBlock(default='Замовити зараз', required=False)), ('cta_anchor', wagtail.blocks.CharBlock(default='#form', help_text='Якорь ссылки, например #form', required=False)), ('use_product_price', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('benefits', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Головні переваги', required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('steps', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Як замовити?', required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock())])))])), ('form', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='ЗАЛИШИТИ ЗАЯВКУ', required=False)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('submit_text', wagtail.blocks.CharBlock(default='Залишити заявку', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
