# Generated by Django 4.2.7 on 2025-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_alter_productlandingpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersuccesspage',
            name='meta_pixel_code',
            field=models.TextField(blank=True, help_text='Вставьте полный код пикселя Meta/Facebook (будет добавлен в <head>)'),
        ),
        migrations.AddField(
            model_name='ordersuccesspage',
            name='tiktok_pixel_code',
            field=models.TextField(blank=True, help_text='Вставьте полный код пикселя TikTok (будет добавлен в <head>)'),
        ),
        migrations.AddField(
            model_name='productlandingpage',
            name='meta_pixel_code',
            field=models.TextField(blank=True, help_text='Вставьте полный код пикселя Meta/Facebook (будет добавлен в <head>)'),
        ),
        migrations.AddField(
            model_name='productlandingpage',
            name='tiktok_pixel_code',
            field=models.TextField(blank=True, help_text='Вставьте полный код пикселя TikTok (будет добавлен в <head>)'),
        ),
    ]
