# Generated by Django 4.2.26 on 2025-11-16 15:07

from django.db import migrations
import eshop.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_alter_homepage_body_alter_productlandingpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('old_price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('product_chooser', wagtail.snippets.blocks.SnippetChooserBlock(eshop.models.Product, help_text='Выберите продукт для автозаполнения полей (опционально)')), ('page_chooser', wagtail.blocks.PageChooserBlock(help_text='Выберите страницу для кнопки (опционально)', required=False)), ('button_text', wagtail.blocks.CharBlock(default='Подробнее', required=False)), ('button_url', wagtail.blocks.URLBlock(help_text='URL для кнопки (если не выбрана страница)', required=False))])), ('hero_product', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('old_price', wagtail.blocks.DecimalBlock(decimal_places=2, max_digits=10, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('product_chooser', wagtail.snippets.blocks.SnippetChooserBlock(eshop.models.Product, help_text='Выберите продукт для автозаполнения полей (опционально)')), ('page_chooser', wagtail.blocks.PageChooserBlock(help_text='Выберите страницу для кнопки (опционально)', required=False)), ('button_text', wagtail.blocks.CharBlock(default='Подробнее', required=False)), ('button_url', wagtail.blocks.URLBlock(help_text='URL для кнопки (если не выбрана страница)', required=False))])), ('featured', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('max_items', wagtail.blocks.IntegerBlock(default=8, max_value=24, min_value=1, required=False))])), ('grid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('category_slug', wagtail.blocks.CharBlock(help_text='Slug категории для фильтрации (опционально)', required=False)), ('product_chooser', wagtail.blocks.PageChooserBlock(help_text='Выберите конкретный продукт (опционально)', page_type=['landing.ProductLandingPage'], required=False)), ('show_prices', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('testimonials', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('author', wagtail.blocks.CharBlock(required=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.TextBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(default='Заказать'))]))], blank=True, use_json_field=True),
        ),
    ]
