# Generated by Django 4.2.26 on 2025-11-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('landing', '0030_homepage_company_logo_homepage_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='company_logo',
            field=models.ForeignKey(blank=True, help_text='Логотип компании для хедера', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='company_name',
            field=models.CharField(blank=True, help_text='Название компании для хедера', max_length=100),
        ),
    ]
