# Generated by Django 4.2.7 on 2025-11-04 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop', '0007_historicalorder_conversion_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('utm_source', models.CharField(db_index=True, max_length=64)),
                ('utm_medium', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('utm_source', 'utm_medium', 'utm_campaign')},
            },
        ),
        migrations.CreateModel(
            name='TikTokMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('landing_page', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='analytics.tiktokcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='analytics.tiktokcampaign')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='eshop.order')),
            ],
        ),
    ]
