# Generated by Django 4.2.7 on 2025-11-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokcampaign',
            name='external_campaign_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
