# Generated by Django 4.2.7 on 2025-11-04 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\-\\s\\(\\)]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
