# Generated by Django 4.2.7 on 2025-11-04 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_backfill_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
