# Generated by Django 4.2.7 on 2025-11-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_orderitem_shipped_quantity_ordercomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='conversion_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='tiktok_source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='conversion_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tiktok_source',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
