# Generated by Django 4.2.7 on 2025-11-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_historicalorder_conversion_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('utm_medium', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, max_length=128)),
                ('ttclid', models.CharField(blank=True, max_length=128)),
                ('fbp', models.CharField(blank=True, max_length=128)),
                ('fbc', models.CharField(blank=True, max_length=128)),
                ('landing_url', models.URLField(blank=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='eshop.order')),
            ],
        ),
    ]
