# Generated by Django 4.2.26 on 2026-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='block_id',
            field=models.CharField(blank=True, help_text='Block/Record ID', max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='lead',
            name='fbclid',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='lead',
            name='office',
            field=models.CharField(blank=True, help_text='Office/Warehouse ID', max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='External transaction ID', max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
